# ============================================================================================================================
# Provisionamento do Projeto - POP-CE
# Arquivo: prov_zbxproxy.yml
# Descrição: Este arquivo é responsável por provisionar a instalação do Zabbix Proxy, Zabbix Agent e suas configurações.
# ============================================================================================================================
---
- name: Configurar Zabbix Proxy e Agent
  hosts: all
  become: yes

  # --- PRE-TASKS: Verificação e Instalação de Dependências ---
  pre_tasks:
    - name: Verificar se a collection community.zabbix está instalada
      ansible.builtin.command: ansible-galaxy collection list community.zabbix
      register: zabbix_collection_check
      changed_when: false
      failed_when: false # Ignora o erro se a collection não for encontrada
      connection: local # Roda na máquina que está executando o playbook
      run_once: true    # Roda apenas uma vez, não para cada host

    - name: Instalar a collection community.zabbix se necessário
      ansible.builtin.command: ansible-galaxy collection install community.zabbix
      when: zabbix_collection_check.rc != 0 # Roda apenas se o comando anterior falhou
      connection: local
      run_once: true

  # --- TASKS: Execução das Roles ---
  tasks:
    - name: Executar role setup_context
      include_role:
        name: setup_context

    - name: Executar role net_security
      include_role:
        name: net_security

    - name: Executar role zabbix_proxy
      include_role:
        name: zabbix_proxy

    - name: Executar role zabbix_agent
      include_role:
        name: zabbix_agent
        
    - name: Executar role zabbix_server_register_proxy
      include_role:
        name: zabbix_server_register_proxy