# ============================================================================================================================
# Provisionamento do Projeto - POP-CE
# Arquivo: zbxproxy_ce/prov_zbxproxy.yml
# Descrição: Este arquivo é responsável por provisionar a instalação do Zabbix Proxy, Zabbix Agent e suas configurações.
# A ordem das roles importa.
# ============================================================================================================================
---
- name: Configurar Zabbix Proxy e Agent
  hosts: all
  become: yes
  tasks:
    - name: Executar role setup_context
      include_role:
        name: setup_context

    - name: Executar role net_security
      include_role:
        name: net_security

    - name: Executar role zabbix_proxy
      include_role:
        name: zabbix_proxy

    - name: Executar role zabbix_agent
      include_role:
        name: zabbix_agent
        
    - name: Executar role zabbix_server_register_proxy
      include_role:
        name: zabbix_server_register_proxy