# ============================================================================================================================
# Provisionamento do Projeto - POP-CE
# Arquivo: zbxproxy_ce/prov_zbxproxy.yml
# Descrição: Este arquivo é responsável por provisionar a instalação do Zabbix Proxy, Zabbix Agent e suas configurações.
# A ordem das roles importa.
# ============================================================================================================================
---
- name: Provisionar a instalação, configuração e registro do Zabbix Proxy. 
  hosts: all
  become: yes
  gather_facts: yes
  vars_files:
    - group_vars/all.yml
  roles:
    # Passo 1: Descobre a localidade e carrega as variáveis (ex: group_vars/ce.yml)
    - role: setup_context

    # Passo 2: Configura a rede e segurança na máquina
    - role: net_security

    # Passo 3: Instala o proxy e CRIA os fatos com a chave PSK
    - role: zabbix_proxy

    # Passo 4: Instala o agent
    - role: zabbix_agent

    # Passo 5: USA os fatos criados no Passo 3 para se registrar na API do Zabbix Server
    - role: zabbix_server_register_proxy