---


# ==============================================================================
# Tasks da Role 'net_security'
# Arquivo: roles/net_security/tasks/main.yml
# Descrição: Configurações de segurança de rede, incluindo SSH, UFW, e Fail2Ban
# ==============================================================================

# --- Verificar se o SSH está instalado ---
- name: Verificar se o SSH está instalado
  ansible.builtin.package:
    name: openssh-server
    state: present

# --- Configurar SSH ---
- name: Configurar SSH com o template sshd_config
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
  notify: Reiniciar SSH

- name: Configurar banner SSH com issue.net
  ansible.builtin.template:
    src: issue.net.j2
    dest: /etc/issue.net
    owner: root
    group: root
    mode: '0644'
  notify: Reiniciar SSH

# --- Validar configuração do SSH ---
- name: Validar configuração do SSH
  ansible.builtin.command: sshd -t
  changed_when: false
  register: sshd_test
  failed_when: sshd_test.rc != 0

# --- Habilitar e iniciar o serviço SSH ---
- name: Habilitar e iniciar SSH
  ansible.builtin.systemd:
    name: sshd
    enabled: yes
    state: started

# --- Verificar se o UFW está instalado ---
- name: Verificar se o UFW está instalado
  ansible.builtin.package:
    name: ufw
    state: present

# --- Habilitar IPv6 no UFW ---
- name: Configurar UFW para suportar IPv6
  ansible.builtin.lineinfile:
    path: /etc/default/ufw
    regexp: '^IPV6='
    line: 'IPV6=yes'
  notify: Reiniciar UFW

# --- Configurar política padrão do UFW para entrada (deny) ---
- name: Configurar política padrão do UFW para entrada (deny)
  ansible.builtin.ufw:
    default: deny
    direction: incoming

# --- Configurar política padrão do UFW para saída (deny) ---
- name: Configurar política padrão do UFW para saída (deny)
  ansible.builtin.ufw:
    default: deny
    direction: outgoing

# --- Aplicar regras do UFW definidas em group_vars ---
- name: Aplicar regras do UFW
  ansible.builtin.ufw:
    rule: "{{ item.rule }}"
    from_ip: "{{ item.from | default(omit) }}"
    to_ip: "{{ item.to | default(omit) }}"
    port: "{{ item.port | default(omit) }}"
    proto: "{{ item.proto | default(omit) }}"
    direction: "{{ item.direction | default('in') }}"
    comment: "{{ item.comment | default(omit) }}"
  loop: "{{ ufw_rules }}"
  when: ufw_rules is defined

# --- Habilitar UFW ---
- name: Habilitar UFW
  ansible.builtin.ufw:
    state: enabled

# --- Configurar Fail2Ban ---
- name: Instalar Fail2Ban
  ansible.builtin.package:
    name: fail2ban
    state: present

- name: Configurar Fail2Ban para SSH
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify: Reiniciar Fail2Ban

- name: Habilitar e iniciar Fail2Ban
  ansible.builtin.systemd:
    name: fail2ban
    enabled: yes
    state: started
=