# ==============================================================================
# GT Monitoramento 2025
# Role 'zabbix_server_register_proxy' - versão revisada
# ==============================================================================
---
- name: Dependências | Garantir que o gerenciador de pacotes PIP para Python 3 esteja instalado
  become: yes
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Dependências | Garantir que a biblioteca zabbix-api do Python esteja instalada
  ansible.builtin.pip:
    name: zabbix-api
    state: present
    extra_args: --break-system-packages

- name: API | Registrar este Proxy no Zabbix Server
  ansible.builtin.uri:
    url: "{{ zabbix_server_url }}/api_jsonrpc.php"
    method: POST
    headers:
      Content-Type: "application/json-rpc"
      Authorization: "Bearer {{ zabbix_api_token }}"
    body_format: json
    body:
      jsonrpc: "2.0"
      method: "proxy.create"
      params:
        host: "{{ zabbix_proxy_hostname }}"   # Zabbix usa 'host' para proxies também
        description: "Proxy {{ zabbix_proxy_hostname }} provisionado via Ansible"
        tls_connect: 2   # 2 = PSK
        tls_accept: 2
        tls_psk_identity: "{{ proxy_api_psk_identity }}"
        tls_psk: "{{ proxy_api_psk_key }}"
        interface:
          dns: ""
          ip: "127.0.0.1"   # IP fictício, proxy ativo não usa interface
          port: "10051"
          useip: 1
      id: 1
    validate_certs: no
  register: zabbix_api_response
  when: proxy_api_psk_key is defined

- name: Debug | Exibir resposta da criação do Proxy
  ansible.builtin.debug:
    var: zabbix_api_response.json
  when: zabbix_api_response is defined
