# ======================================================================
# GT Monitoramento 2025
# Role: zabbix_server_register_proxy (versão otimizada)
# ======================================================================
---

# ----------------------------------------------------------------------
# Instalação de Dependências
# ----------------------------------------------------------------------
- name: Garantir que o PIP esteja instalado
  become: yes
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Garantir que a biblioteca zabbix-api esteja instalada
  ansible.builtin.pip:
    name: zabbix-api
    state: present
    extra_args: --break-system-packages

# ----------------------------------------------------------------------
# Verificação do Proxy
# ----------------------------------------------------------------------
- name: API | Verificar se o Proxy já está cadastrado no Zabbix Server
  ansible.builtin.uri:
    url: "{{ zabbix_server_url }}/api_jsonrpc.php"
    method: POST
    headers:
      Content-Type: "application/json-rpc"
      Authorization: "Bearer {{ zabbix_api_token }}"
    body_format: json
    body:
      jsonrpc: "2.0"
      method: "proxy.get"
      params:
        output: ["proxyid","name"]
        filter:
          name: ["{{ zabbix_proxy_hostname }}"]
      id: 1
    validate_certs: no
  register: zabbix_proxy_get_response
  when: proxy_api_psk_key is defined

# ----------------------------------------------------------------------
# Criação do Proxy (apenas se não existir)
# ----------------------------------------------------------------------
- name: API | Criar o Proxy se não existir
  ansible.builtin.uri:
    url: "{{ zabbix_server_url }}/api_jsonrpc.php"
    method: POST
    headers:
      Content-Type: "application/json-rpc"
      Authorization: "Bearer {{ zabbix_api_token }}"
    body_format: json
    body:
      jsonrpc: "2.0"
      method: "proxy.create"
      params:
        name: "{{ zabbix_proxy_hostname }}"
        description: "Proxy {{ zabbix_proxy_hostname }} provisionado via Ansible"
        operating_mode: "{{ proxy_operating_mode | default(1) }}"   # 0=ativo, 1=passivo
        tls_connect: "{{ proxy_tls_connect | default(2) }}"        # 1=desabilitado, 2=PSK
        tls_accept: "{{ proxy_tls_accept | default(1) }}"          # 1=ativo
        tls_psk_identity: "{{ proxy_api_psk_identity }}"
        tls_psk: "{{ proxy_api_psk_key }}"
      id: 1
    validate_certs: no
  register: zabbix_proxy_create_response
  when:
    - proxy_api_psk_key is defined
    - zabbix_proxy_get_response.json.result is defined
    - zabbix_proxy_get_response.json.result | length == 0

# ----------------------------------------------------------------------
# Debug final
# ----------------------------------------------------------------------
- name: Debug | Exibir resposta da API
  ansible.builtin.debug:
    msg: >-
      {% if zabbix_proxy_create_response is defined %}
        {{ zabbix_proxy_create_response.json }}
      {% else %}
        {{ zabbix_proxy_get_response.json }}
      {% endif %}
  when: proxy_api_psk_key is defined
