# ====================================================================
# Registrar Proxy no Zabbix Server usando API e PSK
# ====================================================================

- name: API | Autenticar no Zabbix Server
  ansible.builtin.uri:
    url: "{{ zabbix_server_url }}/api_jsonrpc.php"
    method: POST
    headers:
      Content-Type: "application/json-rpc"
    body_format: json
    body:
      jsonrpc: "2.0"
      method: "user.login"
      params:
        username: "{{ zabbix_api_user }}"
        password: "{{ zabbix_api_password }}"
      id: 1
  register: zabbix_auth_response

- name: Set fact | Salvar token de autenticação
  ansible.builtin.set_fact:
    zabbix_auth_token: "{{ zabbix_auth_response.json.result }}"

# 2. Criar o proxy com PSK
- name: API | Criar proxy no Zabbix Server
  ansible.builtin.uri:
    url: "{{ zabbix_server_url }}/api_jsonrpc.php"
    method: POST
    headers:
      Content-Type: "application/json-rpc"
    body_format: json
    body:
      jsonrpc: "2.0"
      method: "proxy.create"
      params:
        host: "{{ zabbix_proxy_hostname }}"
        status: 5
        description: "Proxy provisionado via Ansible"
        tls_connect: 2
        tls_accept: 2
        tls_psk_identity: "{{ proxy_api_psk_identity }}"
        tls_psk: "{{ proxy_api_psk_key }}"
      auth: "{{ zabbix_auth_response.json.result }}"
      id: 1
  register: zabbix_proxy_create_response

- name: Debug | Resposta da API do Zabbix
  ansible.builtin.debug:
    var: zabbix_proxy_create_response.json
