# ==============================================================================
# GT Monitoramento 2025
# Tasks da Role 'zabbix_server_register_proxy' (Versão Ajustada)
# ==============================================================================
---
# ======================================================================
# --- Instalação de Dependências ---
# ======================================================================
- name: Dependências | Garantir que o PIP esteja instalado
  become: yes
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Dependências | Garantir que a biblioteca zabbix-api esteja instalada
  ansible.builtin.pip:
    name: zabbix-api
    state: present
    extra_args: --break-system-packages

# ======================================================================
# --- Verificação e Registro do Proxy ---
# ======================================================================
- name: API | Verificar se o Proxy já está cadastrado no Zabbix Server
  ansible.builtin.uri:
    url: "{{ zabbix_server_url }}/api_jsonrpc.php"
    method: POST
    headers:
      Content-Type: "application/json-rpc"
      Authorization: "Bearer {{ zabbix_api_token }}"
    body_format: json
    body:
      jsonrpc: "2.0"
      method: "proxy.get"
      params:
        output: ["proxyid","name"]
        filter:
          name: ["{{ zabbix_proxy_hostname }}"]
      id: 1
    validate_certs: no
  register: zabbix_proxy_get_response
  when: proxy_api_psk_key is defined

- name: API | Criar o Proxy (se não for encontrado)
  ansible.builtin.uri:
    url: "{{ zabbix_server_url }}/api_jsonrpc.php"
    method: POST
    headers:
      Content-Type: "application/json-rpc"
      Authorization: "Bearer {{ zabbix_api_token }}"
    body_format: json
    body:
      jsonrpc: "2.0"
      method: "proxy.create"
      params:
        name: "{{ zabbix_proxy_hostname }}"
        description: "Proxy {{ zabbix_proxy_hostname }} provisionado via Ansible"
        tls_connect: 2
        tls_accept: 2
        tls_psk_identity: "{{ proxy_api_psk_identity }}"
        tls_psk: "{{ proxy_api_psk_key }}"
        # Não usamos "interfaces", apenas os parâmetros compatíveis com a API do Zabbix
      id: 1
    validate_certs: no
  register: zabbix_proxy_create_response
  when:
    - proxy_api_psk_key is defined
    - zabbix_proxy_get_response.json.result is defined
    - zabbix_proxy_get_response.json.result | length == 0

- name: Debug | Exibir resposta da API
  ansible.builtin.debug:
    msg: >-
      {% if zabbix_proxy_create_response is defined %}
        {{ zabbix_proxy_create_response.json }}
      {% else %}
        {{ zabbix_proxy_get_response.json }}
      {% endif %}
  when: proxy_api_psk_key is defined
