# ==============================================================================
# GT Monitoramento 2025
# Tasks da Role 'zabbix_server_register_proxy'
# Arquivo: roles/zabbix_server_register_proxy/tasks/main.yml
# ==============================================================================
---
- name: API | Registrar este Proxy no Zabbix Server
  community.zabbix.zabbix_proxy:
    server_url: "{{ zabbix_server_url }}"
    login_user: "{{ zabbix_api_user }}"
    login_password: "{{ zabbix_api_password }}"
    proxy_name: "{{ zabbix_proxy_hostname }}"
    status: "active"
    description: "Proxy {{ zabbix_proxy_hostname }} provisionado via Ansible em {{ ansible_date_time.iso8601 }}"
    tls_connect: "{{ zabbix_proxy_tls_connect | upper }}"
    tls_accept: "{{ zabbix_proxy_tls_accept | upper }}"
    tls_psk_identity: "{{ proxy_api_psk_identity }}"
    tls_psk: "{{ proxy_api_psk_key }}"
    state: present
  delegate_to: localhost
  run_once: true
  when: proxy_api_psk_key is defined