# ======================================================================
# GT Monitoramento 2025
# Arquivo: roles/zabbix_server_register_proxy/tasks/main.yml
# ======================================================================
---
# Este código cria o proxy sem a interface para contornar a API inconsistente do Zabbix Server.

- name: Garantir que o PIP esteja instalado
  become: yes
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Garantir que a biblioteca zabbix-api esteja instalada
  ansible.builtin.pip:
    name: zabbix-api
    state: present
    extra_args: --break-system-packages

- name: API | Verificar se o Proxy já existe
  ansible.builtin.uri:
    url: "{{ zabbix_server_url }}/api_jsonrpc.php"
    method: POST
    headers:
      Content-Type: "application/json-rpc"
      Authorization: "Bearer {{ zabbix_api_token }}"
    body_format: json
    body:
      jsonrpc: "2.0"
      method: "proxy.get"
      params:
        output: "extend"
        filter:
          name: ["{{ zabbix_proxy_hostname }}"]
      id: 1
    # validate_certs: no     # deixe comentado se estiver usando HTTP; habilite se for HTTPS self-signed
    follow_redirects: all
  register: zabbix_proxy_get_response
  failed_when: "'error' in zabbix_proxy_get_response.json"

- name: API | Criar o Proxy (sem interface) se não existir
  ansible.builtin.uri:
    url: "{{ zabbix_server_url }}/api_jsonrpc.php"
    method: POST
    headers:
      Content-Type: "application/json-rpc"
      Authorization: "Bearer {{ zabbix_api_token }}"
    body_format: json
    body:
      jsonrpc: "2.0"
      method: "proxy.create"
      params:
        name: "{{ zabbix_proxy_hostname }}"
        description: "Proxy {{ zabbix_proxy_hostname }} provisionado via Ansible"
        operating_mode: "{{ zabbix_proxy_mode | default(0) | int }}"
        tls_connect: "{{ zabbix_proxy_tls_connect | default(1) | int }}"
        tls_accept: "{{ zabbix_proxy_tls_accept | default(1) | int }}"
        tls_psk_identity: >-
          {{
            ((zabbix_proxy_tls_connect | int) == 1 or (zabbix_proxy_tls_accept | int) in [1,3])
            | ternary(zabbix_proxy_psk_identity, omit)
          }}
        tls_psk: >-
          {{
            ((zabbix_proxy_tls_connect | int) == 1 or (zabbix_proxy_tls_accept | int) in [1,3])
            | ternary(proxy_api_psk_key, omit)
          }}
      id: 2
    # validate_certs: no
    follow_redirects: all
  register: zabbix_proxy_create_response
  failed_when: "'error' in zabbix_proxy_create_response.json"
  when: (zabbix_proxy_get_response.json.result | default([])) | length == 0

- name: Final | Exibir resultado da operação
  ansible.builtin.debug:
    msg: "AVISO: Proxy '{{ zabbix_proxy_hostname }}' criado/verificado com sucesso. A interface (IP) deve ser configurada manualmente na interface web do Zabbix."
