---
# ==============================================================================
# Tasks da Role 'pre_checks'
# Arquivo: roles/pre_checks/tasks/main.yml
# ... (restante do cabeçalho)
# ==============================================================================

# --- Verificação de Conectividade ---
# Esta tarefa simples executa um teste de ping para cada IP na lista
# `connectivity_test_ips`. A execução não será interrompida se algum ping falhar.
- name: Testar a conectividade com os IPs de destino
  ansible.builtin.command: "ping -c 3 {{ item }}"
  loop: "{{ connectivity_test_ips }}"
  register: ping_results
  changed_when: false
  ignore_errors: true  # Permite que o playbook continue mesmo se uma tarefa falhar

# --- Exibir Resultados dos Testes ---
# Mostra o resultado do teste para cada IP, indicando se foi bem-sucedido ou não.
- name: Mostrar resultados dos testes de conectividade
  ansible.builtin.debug:
    msg: "Teste para {{ item.item }}: {{ item.rc == 0 | ternary('Sucesso', 'Falha') }}"
  loop: "{{ ping_results.results }}"
