# ==============================================================================
# Task para a Role 'zabbix_proxy'
# Arquivo: roles/zabbix_proxy/tasks/main.yml
# ==============================================================================

# ==============================================================================
# --- Instalação do Repositório Zabbix ---
# ==============================================================================
- name: Verificar se o repositório Zabbix já está instalado
  ansible.builtin.stat:
    path: "/etc/apt/sources.list.d/zabbix.list"
  register: zabbix_repo_status
  changed_when: false

- name: Baixar e instalar o pacote do repositório Zabbix
  ansible.builtin.apt:
    deb: "{{ zabbix_repo_url }}"
    state: present
  when: not zabbix_repo_status.stat.exists

# ==============================================================================
# --- Instalação e Configuração do Zabbix Proxy ---
# ==============================================================================
- name: Atualizar cache de pacotes
  ansible.builtin.apt:
    update_cache: yes

- name: Instalar Zabbix Proxy com SQLite
  ansible.builtin.apt:
    name: "{{ zabbix_proxy_package }}"
    state: present

- name: Criar diretórios necessários
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: zabbix
    group: zabbix
    mode: '0755'
  loop:
    - "{{ zabbix_proxy_dbname | dirname }}"
    - "{{ zabbix_proxy_logfile | dirname }}"
    - "{{ zabbix_proxy_socket_dir }}"

# ==============================================================================
# --- Geração e Configuração da Chave PSK ---
# ==============================================================================
- name: Verificar status do arquivo PSK do proxy
  ansible.builtin.stat:
    path: "{{ zabbix_proxy_psk_file }}"
  register: proxy_psk_file_status
  changed_when: false

- name: Criar diretório para o arquivo PSK do proxy
  ansible.builtin.file:
    path: "{{ zabbix_proxy_psk_file | dirname }}"
    state: directory
    owner: zabbix
    group: zabbix
    mode: '0755'
  when: not proxy_psk_file_status.stat.exists

- name: Gerar valor da chave PSK (somente se o arquivo não existir)
  ansible.builtin.command: openssl rand -hex 32
  register: proxy_psk_value_raw
  when: not proxy_psk_file_status.stat.exists
  changed_when: true

- name: Ler chave PSK existente do arquivo
  ansible.builtin.slurp:
    src: "{{ zabbix_proxy_psk_file }}"
  register: proxy_psk_file_content
  when: proxy_psk_file_status.stat.exists
  changed_when: false

- name: Definir identidade e chave PSK como fatos
  ansible.builtin.set_fact:
    proxy_api_psk_identity: "{{ zabbix_proxy_psk_identity }}"
    proxy_api_psk_key: >-
      {{ (proxy_psk_file_status.stat.exists)
         | ternary((proxy_psk_file_content.content | b64decode | trim),
                   (proxy_psk_value_raw.stdout | default(''))) }}
    cacheable: yes

- name: Criar arquivo PSK (somente se o arquivo não existir)
  ansible.builtin.copy:
    content: "{{ proxy_api_psk_key }}"
    dest: "{{ zabbix_proxy_psk_file }}"
    owner: zabbix
    group: zabbix
    mode: '0600'
  when: not proxy_psk_file_status.stat.exists

- name: Exibir valor da chave PSK usada (debug)
  ansible.builtin.debug:
    var: proxy_api_psk_key

# ==============================================================================
# --- Aplicar configuração do Zabbix Proxy ---
# ==============================================================================
- name: Aplicar configuração do Zabbix Proxy
  ansible.builtin.template:
    src: zabbix_proxy.conf.j2
    dest: /etc/zabbix/zabbix_proxy.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reiniciar Zabbix Proxy

# ==============================================================================
# --- Gestão do Serviço ---
# ==============================================================================
- name: Habilitar e iniciar Zabbix Proxy
  ansible.builtin.systemd:
    name: zabbix-proxy
    enabled: yes
    state: started
