---
# ============================================================================== 
# Tasks da Role 'zabbix_agent' - Modificado
# Arquivo: roles/zabbix_agent/tasks/main.yml
# ==============================================================================

# ============================================================================== 
# --- Instalação do Zabbix Agent ---
# ============================================================================== 
- name: Instalar Zabbix Agent
  ansible.builtin.apt:
    name: "{{ zabbix_agent_package }}"
    state: present
    update_cache: yes

# ============================================================================== 
# --- Criar diretório para PID e socket ---
# ============================================================================== 
- name: Criar diretório para PID e socket do Zabbix Agent
  ansible.builtin.file:
    path: "/run/zabbix"
    state: directory
    owner: zabbix
    group: zabbix
    mode: '0755'

# ============================================================================== 
# --- Geração e Configuração da Chave PSK ---
# ============================================================================== 
- name: Verificar status do arquivo PSK do agente
  ansible.builtin.stat:
    path: "{{ zabbix_agent_psk_file }}"
  register: agent_psk_file_status
  changed_when: false

- name: Criar diretório para o arquivo PSK do agente
  ansible.builtin.file:
    path: "{{ zabbix_agent_psk_file | dirname }}"
    state: directory
    owner: zabbix
    group: zabbix
    mode: '0755'
  when: not agent_psk_file_status.stat.exists

- name: Gerar e salvar valor da chave PSK
  ansible.builtin.shell: openssl rand -hex 32
  register: agent_psk_value
  when: not agent_psk_file_status.stat.exists
  changed_when: true

- name: Exibir valor da chave PSK do agente
  ansible.builtin.debug:
    msg: "VALOR DA CHAVE PSK DO AGENTE: {{ agent_psk_value.stdout }}"
  when: not agent_psk_file_status.stat.exists

- name: Criar arquivo PSK e definir permissões
  ansible.builtin.copy:
    content: "{{ agent_psk_value.stdout }}"
    dest: "{{ zabbix_agent_psk_file }}"
    owner: zabbix
    group: zabbix
    mode: '0600'
  when: not agent_psk_file_status.stat.exists

# ============================================================================== 
# --- Configuração do Zabbix Agent ---
# ============================================================================== 
- name: Configurar Zabbix Agent
  ansible.builtin.template:
    src: zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reiniciar Zabbix Agent

# ============================================================================== 
# --- Gestão do Serviço ---
# ============================================================================== 
- name: Habilitar e iniciar Zabbix Agent
  ansible.builtin.systemd:
    name: zabbix-agent2
    enabled: yes
    state: started
    daemon_reload: yes
