# ======================================================================
# GT Monitoramento 2025
# Arquivo: roles/zabbix_server_register_agent/tasks/main.yml
# Descrição: Registra/atualiza host do Zabbix Agent 2 no Zabbix Server.
# ======================================================================
---
# roles/zabbix_server_register_agent_simple/tasks/main.yml
---
# 0) Dependências locais
- name: Garantir python3-pip instalado
  become: yes
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Garantir biblioteca requests instalada
  become: yes
  ansible.builtin.pip:
    name: requests
    state: present
    extra_args: --break-system-packages

- name: Garantir collection community.zabbix instalada
  ansible.builtin.command: ansible-galaxy collection install community.zabbix -f
  args:
    creates: "{{ lookup('env','HOME') }}/.ansible/collections/ansible_collections/community/zabbix"

# 1) Ler PSK do agente
- name: Ler PSK do agente
  ansible.builtin.slurp:
    src: "{{ zabbix_agent_psk_file }}"
  register: agent_psk

- name: Definir fato com PSK (64 hex)
  ansible.builtin.set_fact:
    agent_psk_key: "{{ (agent_psk.content | b64decode) | trim }}"

# 2) Registrar/atualizar host no Zabbix
- name: Registrar/atualizar host do agente no Zabbix
  vars:
    # Conexão httpapi para community.zabbix
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_use_ssl: false
    ansible_httpapi_validate_certs: false
    ansible_zabbix_url_path: "zabbix"
    ansible_host: "{{ zabbix_server_ip }}"
    ansible_zabbix_auth_key: "{{ zabbix_api_token }}"

  community.zabbix.zabbix_host:
    state: present
    status: enabled
    host_name: "{{ zabbix_agent_hostname }}"
    visible_name: "{{ zabbix_agent_hostname }}"
    host_groups: "{{ zabbix_agent_hostgroups }}"
    link_templates: "{{ zabbix_agent_templates }}"
    monitored_by: proxy
    proxy: "{{ zabbix_proxy_hostname }}"
    interfaces:
      - type: agent
        main: 1
        useip: 1
        ip: "{{ zabbix_agent_source_ip }}"
        dns: ""
        port: "10050"
    tls_connect: 2           # PSK
    tls_accept: 2            # PSK
    tls_psk_identity: "{{ zabbix_agent_psk_identity }}"
    tls_psk: "{{ agent_psk_key }}"
