---
# ==============================================================================
# Task para a Role 'setup_context'
# Arquivo: roles/setup_context/tasks/main.yml
# ==============================================================================
- name: Setup | Determinar a localidade a partir do grupo do inventário
  ansible.builtin.set_fact:
    # Pega o primeiro grupo ao qual o host pertence (ex: 'ce', 'rj', 'sp')
    # Esta variável 'group_names' é fornecida automaticamente pelo Ansible.
    location_code: "{{ group_names[0] }}"

- name: Setup | Carregar variáveis específicas da localidade
  ansible.builtin.include_vars:
    # Usa a variável que acabamos de criar para montar o caminho do arquivo dinamicamente.
    file: "group_vars/{{ location_code }}.yml"
  # Se o arquivo (ex: group_vars/ce.yml) não existir, o playbook vai parar com um erro claro.
  ignore_errors: no