---
#========================================================================
# Handlers da Role 'net_security'
# Arquivo: roles/net_security/handlers/main.yml
# ==============================================================================

- name: Reiniciar Networking
  ansible.builtin.systemd:
    name: systemd-networkd
    state: restarted

- name: Reiniciar Fail2Ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
    enabled: yes

- name: Reiniciar SSH
  ansible.builtin.systemd:
    name: sshd
    state: restarted
    enabled: yes

- name: Reiniciar UFW
  ansible.builtin.ufw:
    state: reloaded

- name: Atualizar MOTD
  ansible.builtin.command: run-parts /etc/update-motd.d
  changed_when: true
