---
# ==============================================================================
# Handlers da Role 'network_security'
# Arquivo: roles/net_security/handlers/main.yml
# ==============================================================================

# --- Reiniciar serviço de rede (Debian ifupdown) ---
# Tenta via módulo systemd; se falhar, executa systemctl diretamente.
- name: Reiniciar Networking
  block:
    - name: Networking | restart via systemd
      ansible.builtin.systemd:
        name: networking
        state: restarted
      register: _net_restart
      failed_when: false
      changed_when: _net_restart is changed
  rescue:
    - name: Fallback final: systemctl restart networking
      ansible.builtin.command: systemctl restart networking
      register: _net_restart_cmd
      changed_when: true
      failed_when: _net_restart_cmd.rc != 0

# --- Reiniciar serviço Fail2Ban ---
- name: Reiniciar Fail2Ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
    enabled: true

# --- Reiniciar serviço SSH ---
- name: Reiniciar SSH
  ansible.builtin.systemd:
    name: sshd
    state: restarted
    enabled: true

# --- Atualizar MOTD ---
- name: Atualizar MOTD
  ansible.builtin.command: /usr/bin/run-parts --regex '^[0-9]+-.*' /etc/update-motd.d/
  changed_when: false
